# Generated by Django 4.0.4 on 2022-05-02 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_cake_price'),
        ('cart', '0003_rename_sub_total_cartproducts_subtotal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CartProducts',
            new_name='CartProduct',
        ),
    ]
