# Generated by Django 4.0.4 on 2022-05-19 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0005_alter_cart_total_alter_cartproduct_subtotal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered_by', models.CharField(max_length=100)),
                ('shipping_address', models.CharField(max_length=100)),
                ('mobile', models.CharField(max_length=100)),
                ('total', models.PositiveIntegerField()),
                ('order_status', models.CharField(choices=[('delivered', 'delivered'), ('pending', 'pending')], max_length=100)),
                ('cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
            ],
            options={
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
